# Generated by Django 6.0.4 on 2026-04-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        help_text="One-line summary shown on cards.", max_length=240
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full project description shown on detail page."
                    ),
                ),
                (
                    "problem",
                    models.TextField(
                        blank=True, help_text="What problem did this solve?"
                    ),
                ),
                (
                    "solution",
                    models.TextField(blank=True, help_text="How did you solve it?"),
                ),
                (
                    "impact",
                    models.TextField(
                        blank=True, help_text="Measurable outcomes / metrics."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web", "Web Application"),
                            ("website", "Corporate Website"),
                            ("ml", "Machine Learning"),
                            ("automation", "Automation / Tooling"),
                            ("other", "Other"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Concept QA Labs Pvt. Ltd.",
                        max_length=160,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, default="Full-Stack Developer", max_length=120
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/covers/"
                    ),
                ),
                ("live_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Leave blank for ongoing.", null=True
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=True, help_text="Show on home page."),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="CSS color hint: primary, accent, success, warning, or hex like #1f67ff",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Tech Stack Item",
                "verbose_name_plural": "Tech Stack Items",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=240)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=240)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.techstack"
            ),
        ),
    ]
