# Generated by Django 6.0.4 on 2026-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_proprietary",
            field=models.BooleanField(
                default=False,
                help_text="If True and github_url is empty, show “Source private” on the site.",
            ),
        ),
    ]
