# Generated by Django 6.0.4 on 2026-07-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_audit_fixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="roles_and_users",
            field=models.TextField(
                blank=True, help_text="Who uses the system. One role per line."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="scope_notes",
            field=models.TextField(
                blank=True,
                help_text="Honest scope notes (what this is / is not). One note per line.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Short subtitle under the title on the case study page.",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technical_highlights",
            field=models.TextField(
                blank=True,
                help_text="Architecture / technical highlights. One point per line.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="workflows",
            field=models.TextField(
                blank=True, help_text="Core workflows. One step or flow per line."
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(help_text="Overview shown on the detail page."),
        ),
        migrations.AlterField(
            model_name="project",
            name="impact",
            field=models.TextField(
                blank=True, help_text="Measurable outcomes / capability outcomes."
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_proprietary",
            field=models.BooleanField(
                default=False,
                help_text='If True and github_url is empty, show "Source private" on the site.',
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.CharField(
                help_text="One-liner shown on home cards and as the case-study lead.",
                max_length=400,
            ),
        ),
    ]
