# Generated by Django 6.0.4 on 2026-04-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(default="Full-Stack Developer", max_length=120),
                ),
                (
                    "headline",
                    models.CharField(
                        default="Building scalable web applications with Python, Django, and Machine Learning.",
                        max_length=240,
                    ),
                ),
                (
                    "subheadline",
                    models.TextField(
                        default="3+ years of professional experience designing enterprise-grade systems, RESTful APIs, and data-driven applications. Currently expanding into ML and Deep Learning."
                    ),
                ),
                (
                    "typing_phrases",
                    models.TextField(
                        default="Full-Stack Developer\nPython & Django Engineer\nMachine Learning Enthusiast\nAPI Architect",
                        help_text="One phrase per line — used by the typing animation in the hero.",
                    ),
                ),
                (
                    "cta_primary_label",
                    models.CharField(default="View Projects", max_length=60),
                ),
                (
                    "cta_primary_url",
                    models.CharField(default="#projects", max_length=200),
                ),
                (
                    "cta_secondary_label",
                    models.CharField(default="Get in Touch", max_length=60),
                ),
                (
                    "cta_secondary_url",
                    models.CharField(default="/contact/", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Lalu Yashwanth", max_length=120),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Full-Stack Developer | Python & Django Engineer",
                        max_length=240,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        default="Full-Stack Developer specializing in Python, Django, PostgreSQL, REST APIs, and Machine Learning. 3+ years building scalable web applications."
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        default="Full-Stack Developer, Python Developer, Django Developer, PostgreSQL, REST API, Machine Learning, Data Science, Hyderabad",
                        max_length=500,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="laluyashwanth.dev@gmail.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "location",
                    models.CharField(default="Hyderabad, India", max_length=120),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, default="https://github.com/G-Laluyashwanth"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, default="https://linkedin.com/in/laluyashwanth"
                    ),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resume/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
