# Generated by Django 6.0.4 on 2026-07-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="twitter_url",
            field=models.URLField(
                blank=True, default="", help_text="Full URL to your Twitter/X profile."
            ),
        ),
    ]
