# Generated by Django 6.0.4 on 2026-07-04 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_twitter_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "excerpt",
                    models.CharField(
                        blank=True,
                        help_text="One-line summary shown in the list.",
                        max_length=280,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Body of the post. Leave blank if using an external link.",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="If set, the post links here instead of an internal page.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="typing_phrases",
        ),
    ]
