# Generated by Django 6.0.4 on 2026-07-22 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_post_remove_herosection_typing_phrases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="cta_secondary_url",
            field=models.CharField(default="#contact", max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
