# Generated by Django 6.0.4 on 2026-04-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("field_of_study", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "grade",
                    models.CharField(
                        blank=True, help_text="e.g. CGPA 8.4 / 10", max_length=60
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["-end_date", "order"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=160)),
                ("role", models.CharField(max_length=160)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-Time"),
                            ("part_time", "Part-Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("company_url", models.URLField(blank=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="experience/logos/"
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Leave blank for current role.", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="Short overview shown on the timeline."),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True,
                        help_text="One bullet per line - shown as a list on detail.",
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list, e.g. Python, Django, PostgreSQL",
                        max_length=400,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Work Experience",
                "verbose_name_plural": "Work Experience",
                "ordering": ["-start_date", "order"],
            },
        ),
    ]
