# Generated by Django 6.0.4 on 2026-04-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon name (used in template if you wire one in).",
                        max_length=40,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=240)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="advanced",
                        max_length=20,
                    ),
                ),
                (
                    "years_experience",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        help_text="e.g. 3.5",
                        max_digits=4,
                    ),
                ),
                ("is_featured", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="skills.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
    ]
