# Generated by Django 6.0.4 on 2026-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="unique_skill_per_category"
            ),
        ),
    ]
